name: Pipeline Intermedio Multi-Job

on:
  push:
    branches: [ "main" ]

# CRUCIAL: Le damos permiso al pipeline para escribir paquetes (imágenes) en el repositorio
permissions: # Permisos para poder subir la imagen al registry de github.  
  contents: read
  packages: write

jobs:
  # ==========================================
  # JOB 1: VALIDACIÓN (Linter del Dockerfile)
  # ==========================================
  lint-test-extract:
    runs-on: ubuntu-latest
    # AQUÍ DECLARAMOS LAS SALIDAS QUE ESTE JOB VA A OFRECER AL RESTO (Job Outputs)
    outputs:
      tag_dinamico: "${{ steps.generar-tag.outputs.FECHA_TAG }}"

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # Usamos una acción de la comunidad para validar el Dockerfile
      - name: Validar sintaxis del Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./img/Dockerfile
      
      # Creamos un paso intermedio para generar el dato dinámico
      - name: Generar identificador de fecha
        id: generar-tag # El ID es crucial para poder referenciarlo después
        run: |
          # Creamos una fecha en formato AÑO.MES.DIA-HORAMINUTA (ej: 2026.06.22-1530)
          FECHA=$(date +'%Y.%m.%d-%H%M')
          echo "La fecha generada es: $FECHA"
          
          # Sintaxis especial de GitHub para guardar una salida en el paso actual
          echo "FECHA_TAG=$FECHA" >> $GITHUB_OUTPUT    

  # ==========================================
  # JOB 2: CONSTRUCCIÓN Y DISTRIBUCIÓN
  # ==========================================
  build-and-push:
    runs-on: ubuntu-latest
    # CRUCIAL: Este job no arrancará hasta que 'lint-and-test' termine con éxito
    needs: [ lint-and-test ]
    
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # Notarás que volvemos a configurar Buildx porque esta es una máquina virtual NUEVA
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # En un entorno real, aquí usarías tu usuario en minúsculas fijo si tu owner tiene mayúsculas
      - name: Build and push a GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./img/Dockerfile
          push: true
          tags: |
            # LEEMOS EL OUTPUT DEL JOB ANTERIOR: needs.<nombre_job>.outputs.<nombre_output>
            ghcr.io/${{ github.repository_owner }}/my-hello-world:${{ needs.lint-test-extract.outputs.tag_dinamico }}
            # ghcr.io/${{ github.repository_owner }}/hello-world-multi-job:${{ github.sha }}
